### PR TITLE
Add --grep option

### PR DESCRIPTION
**Pull request by apeschar**
This adds a `--grep <regexp>` (short: `-g`) option to filter entries when using the `t d` or `t a` commands. Only the entries that match the specified regular expression are selected.

### CODE REVIEW

**Comment by samg** [comment]
Looks like a useful feature.  Could you add some coverage to the test suite, maybe around https://github.com/samg/timetrap/blob/master/spec/timetrap_spec.rb#L301 and https://github.com/samg/timetrap/blob/master/spec/timetrap_spec.rb#L88?

The failing build looks like an issue with 1.8.7 support in some dependencies and I believe I've resolved it in master.

Thanks!

**Comment by apeschar** [comment]
I'm having some trouble getting the test suite to work. I'm running `cd ../path/to/timetrap && rspec`, but a lot of tests are failing with some error that I wasn't able to debug yet:

```
> ruby -v                                                                 ~/code/timetrap
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
> rspec                                                                   ~/code/timetrap
.........................FFFFFFFFFFF...................................F.F.FFFF..........
......................................

Failures:

  1) Timetrap CLI COMMANDS display text should display the current timesheet
     Failure/Error: Timetrap::Timer.process_time(str)
     NoMethodError:
       undefined method `getlocal' for nil:NilClass
     # ./lib/timetrap/timer.rb:26:in `process_time'
     # ./spec/timetrap_spec.rb:7:in `local_time'
     # ./spec/timetrap_spec.rb:320:in `block (6 levels) in <top (required)>'

[...]
```

Is this anything you've seen before and/or can you give me a pointer?

**Comment by samg** [comment]
Yeah, it looks like there's a problem with the test suite in Ruby 2.2.
I'll look into fixing it.  All tests pass in Ruby 2.1.

**Comment by apeschar** [comment]
I'm not really a ruby native, but eventually I figured out I needed to downgrade to rspec 2.x in order to get the tests to work. I've added some tests now, anyway.

**Comment by samg** [comment]
Thanks!  I think I've resolved the test failures under Ruby 2.2 now as
well.  I'll take a look asap and see about getting this merged and released.

**Comment by tjstankus** [comment]
I pulled this changeset into my fork. Tests pass and it works well, AFAICT. :+1:

**Comment by jostber** [comment]
Any update on if this feature will be added?

**Comment by samg** [comment]
Thanks! released in https://rubygems.org/gems/timetrap/versions/1.10.0

**Pull request merged**
